### ISSUE TITLE
its working?

### ISSUE THREAD

**Issue by lordmen99** [kwontaewan/LiveAuction_Android#1]
Hi bro, any demo from this apps? and how setup it with php server and java socket server

**Comment by kwontaewan** [comment]
hi bro 
Please refer to the repository below for the php server and Java socket related code for this app.
If you have any questions about the code, feel free to ask!

https://github.com/kwontaewan/LiveAuction_WebServer
https://github.com/kwontaewan/LiveAuctionTCPServer

**Comment by lordmen99** [comment]
thank you. btw, how setup for server?

**Comment by lordmen99** [comment]
and table mysql for this https://github.com/kwontaewan/LiveAuction_WebServer ? can u share it please
